/*
 * DIO_Configuration.h
 *
 *  Created on: May 28, 2023
 *      Author: Omar
 */
 /******************configuration file for AVRATmega32***********/
/*******************conffiguration of Data Direction of each pin***************/
/*******************options: DIO_PIN_IN // DIO_PIN_OUT ************/

#ifndef MCAL_LAYER_DIO_DRIVER_DIO_CONFIGURATION_H_
#define MCAL_LAYER_DIO_DRIVER_DIO_CONFIGURATION_H_

#define DIO_PORTA_PIN0_INIT_DIREC	DIO_PIN_OUT
#define DIO_PORTA_PIN1_INIT_DIREC	DIO_PIN_OUT
#define DIO_PORTA_PIN2_INIT_DIREC	DIO_PIN_OUT
#define DIO_PORTA_PIN3_INIT_DIREC	DIO_PIN_OUT
#define DIO_PORTA_PIN4_INIT_DIREC	DIO_PIN_OUT
#define DIO_PORTA_PIN5_INIT_DIREC	DIO_PIN_OUT
#define DIO_PORTA_PIN6_INIT_DIREC	DIO_PIN_OUT
#define DIO_PORTA_PIN7_INIT_DIREC	DIO_PIN_OUT

#define DIO_PORTB_PIN0_INIT_DIREC	DIO_PIN_OUT
#define DIO_PORTB_PIN1_INIT_DIREC	DIO_PIN_OUT
#define DIO_PORTB_PIN2_INIT_DIREC	DIO_PIN_OUT
#define DIO_PORTB_PIN3_INIT_DIREC	DIO_PIN_OUT
#define DIO_PORTB_PIN4_INIT_DIREC	DIO_PIN_OUT
#define DIO_PORTB_PIN5_INIT_DIREC	DIO_PIN_OUT
#define DIO_PORTB_PIN6_INIT_DIREC	DIO_PIN_OUT
#define DIO_PORTB_PIN7_INIT_DIREC	DIO_PIN_OUT

#define DIO_PORTC_PIN0_INIT_DIREC	DIO_PIN_OUT
#define DIO_PORTC_PIN1_INIT_DIREC	DIO_PIN_OUT
#define DIO_PORTC_PIN2_INIT_DIREC	DIO_PIN_OUT
#define DIO_PORTC_PIN3_INIT_DIREC	DIO_PIN_OUT
#define DIO_PORTC_PIN4_INIT_DIREC	DIO_PIN_OUT
#define DIO_PORTC_PIN5_INIT_DIREC	DIO_PIN_OUT
#define DIO_PORTC_PIN6_INIT_DIREC	DIO_PIN_OUT
#define DIO_PORTC_PIN7_INIT_DIREC	DIO_PIN_OUT

#define DIO_PORTD_PIN0_INIT_DIREC	DIO_PIN_OUT
#define DIO_PORTD_PIN1_INIT_DIREC	DIO_PIN_OUT
#define DIO_PORTD_PIN2_INIT_DIREC	DIO_PIN_OUT
#define DIO_PORTD_PIN3_INIT_DIREC	DIO_PIN_OUT
#define DIO_PORTD_PIN4_INIT_DIREC	DIO_PIN_OUT
#define DIO_PORTD_PIN5_INIT_DIREC	DIO_PIN_OUT
#define DIO_PORTD_PIN6_INIT_DIREC	DIO_PIN_OUT
#define DIO_PORTD_PIN7_INIT_DIREC	DIO_PIN_OUT


#endif /* MCAL_LAYER_DIO_DRIVER_DIO_CONFIGURATION_H_ */
